### ISSUE TITLE
unrecognized installment of hicstuff 

### ISSUE THREAD

**Issue by psimion** [koszullab/hicstuff#19]
I installed hicstuff with no  (at least I think so), using either of the following commands:

pip3 install hicstuff
pip3 install -e git+https://github.com/koszullab/hicstuff.git@master#egg=hicstuff

In both cases (and also when using variations in python version and options such as  : "python3.6 -m pip install --no-cache-dir hicstuf"), after the "successfull" installation, no executable can be found in the path, and if I manually add hicstuff location in the path, then hicstuff complains that it can not find yahcp. Maybe the issue has to do with the fact that no python library from the installment of hicstuff appear in the folder "/usr/local/lib/python3.6/dist-packages/" were other python librairies usually appear.

see more info below, and thanks for your help !
Paul

> hicstuff pipeline
zsh: command not found: hicstuff
> which hicstuff
hicstuff not found

> ls -lrth /home/lege/.local/bin/
-rwxrwxr-x 1 lege lege  211 Mar  4 10:23 pytest
-rwxrwxr-x 1 lege lege  211 Mar  4 10:23 py.test
-rwxrwxr-x 1 lege lege  219 Mar  4 10:23 mako-render
-rwxrwxr-x 1 lege lege 2.8K Mar  4 10:23 instagraal-setup
-rwxrwxr-x 1 lege lege  232 Mar  4 10:24 instagraal-polish
-rwxrwxr-x 1 lege lege  226 Mar  4 10:24 instagraal
-rwxrwxr-x 1 lege lege  231 Mar  6 10:59 pip3
-rwxrwxr-x 1 lege lege  231 Mar  6 10:59 pip
-rwxrwxr-x 1 lege lege  231 Mar  6 10:59 pip3.7
-rwxrwxr-x 1 lege lege  13K Mar  6 11:03 yahcp
-rwxrwxr-x 1 lege lege 2.0K Mar  6 11:03 pcr_duplicates
-rwxrwxr-x 1 lege lege  222 Mar  6 11:03 f2py3.6
-rwxrwxr-x 1 lege lege  222 Mar  6 11:03 f2py3
-rwxrwxr-x 1 lege lege  222 Mar  6 11:03 f2py
-rwxrwxr-x 1 lege lege  236 Mar  6 11:03 easy_install-3.6
-rwxrwxr-x 1 lege lege  236 Mar  6 11:03 easy_install
-rwxrwxr-x 1 lege lege  218 Mar  6 11:03 hicstuff

> ls -lrth /home/lege/.local/lib/python3.6/site-packages/hicstuff
drwxrwxr-x 2 lege lege 4.0K Mar  5 18:18 __pycache__
-rw-rw-r-- 1 lege lege  643 Mar  6 11:03 __init__.py
-rw-rw-r-- 1 lege lege  16K Mar  6 11:03 filter.py
-rw-rw-r-- 1 lege lege  14K Mar  6 11:03 digest.py
-rw-rw-r-- 1 lege lege  43K Mar  6 11:03 commands.py
-rw-rw-r-- 1 lege lege 2.8K Mar  6 11:03 view.py
-rw-rw-r-- 1 lege lege   22 Mar  6 11:03 version.py
-rw-rw-r-- 1 lege lege 1.8K Mar  6 11:03 main.py
-rw-rw-r-- 1 lege lege 2.1K Mar  6 11:03 log.py
-rw-rw-r-- 1 lege lege 9.1K Mar  6 11:03 iteralign.py
-rw-rw-r-- 1 lege lege  16K Mar  6 11:03 io.py
-rw-rw-r-- 1 lege lege  65K Mar  6 11:03 hicstuff.py

install output example:
> python3.6 -m pip install --no-cache-dir hicstuff 

Collecting hicstuff
  Downloading https://files.pythonhosted.org/packages/22/6c/eaa48ba5d8f62e8941764a93c43ba44e4672d096fce4309452efe31fdd86/hicstuff-1.0.4-py3-none-any.whl (75kB)
    100% |████████████████████████████████| 81kB 4.3MB/s 
Collecting pandas (from hicstuff)
  Downloading https://files.pythonhosted.org/packages/e6/de/a0d3defd8f338eaf53ef716e40ef6d6c277c35d50e09b586e170169cdf0d/pandas-0.24.1-cp36-cp36m-manylinux1_x86_64.whl (10.1MB)
    100% |████████████████████████████████| 10.1MB 10.2MB/s 
Collecting scipy (from hicstuff)
  Downloading https://files.pythonhosted.org/packages/7f/5f/c48860704092933bf1c4c1574a8de1ffd16bf4fde8bab190d747598844b2/scipy-1.2.1-cp36-cp36m-manylinux1_x86_64.whl (24.8MB)
    100% |████████████████████████████████| 24.8MB 8.4MB/s 
Collecting matplotlib (from hicstuff)
  Downloading https://files.pythonhosted.org/packages/e9/69/f5e05f578585ed9935247be3788b374f90701296a70c8871bcd6d21edb00/matplotlib-3.0.3-cp36-cp36m-manylinux1_x86_64.whl (13.0MB)
    100% |████████████████████████████████| 13.0MB 13.8MB/s 
Collecting biopython (from hicstuff)
  Downloading https://files.pythonhosted.org/packages/28/15/8ac646ff24cfa2588b4d5e5ea51e8d13f3d35806bd9498fbf40ef79026fd/biopython-1.73-cp36-cp36m-manylinux1_x86_64.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 13.5MB/s 
Collecting docopt (from hicstuff)
  Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Collecting numpy (from hicstuff)
  Downloading https://files.pythonhosted.org/packages/35/d5/4f8410ac303e690144f0a0603c4b8fd3b986feb2749c435f7cdbb288f17e/numpy-1.16.2-cp36-cp36m-manylinux1_x86_64.whl (17.3MB)
    100% |████████████████████████████████| 17.3MB 19.6MB/s 
Collecting sklearn (from hicstuff)
  Downloading https://files.pythonhosted.org/packages/1e/7a/dbb3be0ce9bd5c8b7e3d87328e79063f8b263b2b1bfa4774cb1147bfcd3f/sklearn-0.0.tar.gz
Collecting pysam (from hicstuff)
  Downloading https://files.pythonhosted.org/packages/f1/fc/d2be1a093bd8494ab63e3168aca36c2494753bbff190f3201ce2e7da9cda/pysam-0.15.2-cp36-cp36m-manylinux1_x86_64.whl (9.6MB)
    100% |████████████████████████████████| 9.6MB 25.3MB/s 
Collecting pytz>=2011k (from pandas->hicstuff)
  Downloading https://files.pythonhosted.org/packages/61/28/1d3920e4d1d50b19bc5d24398a7cd85cc7b9a75a490570d5a30c57622d34/pytz-2018.9-py2.py3-none-any.whl (510kB)
    100% |████████████████████████████████| 512kB 20.7MB/s 
Collecting python-dateutil>=2.5.0 (from pandas->hicstuff)
  Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
    100% |████████████████████████████████| 235kB 30.7MB/s 
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib->hicstuff)
  Downloading https://files.pythonhosted.org/packages/de/0a/001be530836743d8be6c2d85069f46fecf84ac6c18c7f5fb8125ee11d854/pyparsing-2.3.1-py2.py3-none-any.whl (61kB)
    100% |████████████████████████████████| 71kB 37.4MB/s 
Collecting kiwisolver>=1.0.1 (from matplotlib->hicstuff)
  Downloading https://files.pythonhosted.org/packages/69/a7/88719d132b18300b4369fbffa741841cfd36d1e637e1990f27929945b538/kiwisolver-1.0.1-cp36-cp36m-manylinux1_x86_64.whl (949kB)
    100% |████████████████████████████████| 952kB 31.8MB/s 
Collecting cycler>=0.10 (from matplotlib->hicstuff)
  Downloading https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting scikit-learn (from sklearn->hicstuff)
  Downloading https://files.pythonhosted.org/packages/5e/82/c0de5839d613b82bddd088599ac0bbfbbbcbd8ca470680658352d2c435bd/scikit_learn-0.20.3-cp36-cp36m-manylinux1_x86_64.whl (5.4MB)
    100% |████████████████████████████████| 5.4MB 30.6MB/s 
Collecting six>=1.5 (from python-dateutil>=2.5.0->pandas->hicstuff)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting setuptools (from kiwisolver>=1.0.1->matplotlib->hicstuff)
  Downloading https://files.pythonhosted.org/packages/d1/6a/4b2fcefd2ea0868810e92d519dacac1ddc64a2e53ba9e3422c3b62b378a6/setuptools-40.8.0-py2.py3-none-any.whl (575kB)
    100% |████████████████████████████████| 583kB 39.6MB/s 
Installing collected packages: numpy, pytz, six, python-dateutil, pandas, scipy, pyparsing, setuptools, kiwisolver, cycler, matplotlib, biopython, docopt, scikit-learn, sklearn, pysam, hicstuff
  Running setup.py install for docopt ... done
  Running setup.py install for sklearn ... done
Successfully installed biopython-1.73 cycler-0.10.0 docopt-0.6.2 hicstuff-1.0.4 kiwisolver-1.0.1 matplotlib-3.0.3 numpy-1.16.2 pandas-0.24.1 pyparsing-2.3.1 pysam-0.15.2 python-dateutil-2.8.0 pytz-2018.9 scikit-learn-0.20.3 scipy-1.2.1 setuptools-40.8.0 six-1.12.0 sklearn-0.0

**Comment by cmdoret** [comment]
Hello psimion, 

Thanks for the detailed report ! 
I wonder if that could be a permission issue, did you try reinstalling it using `pip install --user hicstuff` ?

**Comment by psimion** [comment]
Hello Cyril,
Unfortunately, i already tried this pip option and it is not the cause of
the issue. Although I do believe it is a permission/user configuration
issue of python.
Indeed, I recently obtained similar problems while trying to install
Funannotate python libraries. So please don't take to much time thinking of
my hicstuff issue, I need to triple-check my python system :(
thank you very much
paul


*----------------*
*Simion Paul*
Postdoctoral research fellow

Laboratory of Evolutionary Genetics and Ecology (LEGE)
Research Unit in Environmental and Evolutionary Biology (URBE)
Department of Biology, University of Namur, Belgium

**Comment by cmdoret** [comment]
Alright then, one easy workaround would be to uninstall hicstuff, install [anaconda](https://www.anaconda.com/distribution/) and reinstall hicstuff with pip when anaconda is active. It will be automatically installed in the default conda environment and that should work despite your permission issues.

**Comment by psimion** [comment]
hello again,

Thank you very much for your help, I finally got hicstuff (and yahcp) to
work. I think it was a problem that only stemmed from my architecture and a
poor use of the combination of [sudo | pip | pip3 | conda environment].
Adding the correct executables (among all the executables already
installed...) to my path seemed to solve it :
export PATH=/home/lege/.local/bin:$PATH

Also, note that running hicstuff yield a missing requirement for yahcp that
(I believe) was not mentionned in the manual : gawk.
/home/lege/.local/bin/yahcp: line 421: gawk: command not found
I simply solved it by installing gawk :
sudo apt-get install gawk

Now that hicstuff works, I could tried instagraal and unfortunately ran
into an issue, I will now create an issue on instagraal github for that
topic.
best, (and thanks again)
Paul


*----------------*
*Simion Paul*
Postdoctoral research fellow

Laboratory of Evolutionary Genetics and Ecology (LEGE)
Research Unit in Environmental and Evolutionary Biology (URBE)
Department of Biology, University of Namur, Belgium

**Comment by psimion** [comment]
Thank you very much for your help, I finally got hicstuff (and yahcp) to work. I think it was a problem that only stemmed from my architecture and a poor use of the combination of [sudo | pip | pip3 | conda environment].
Adding the correct executables (among all the executables I already installed...) to my path seemed to solve it :
export PATH=/home/lege/.local/bin:$PATH
