### ISSUE TITLE
problem with iterative alignment

### ISSUE THREAD

**Issue by Remi-Montagne** [koszullab/hicstuff#20]
I don't know why but it won't align my yeast bank iteratively. here is the log:

> LOGFILE: hicstuff_pipeline//AT192_20190307164922.log
> Performing alignment and generating bed files...
> INFO :: 38014884.0 reads to parse
> INFO :: 
> ----------
> n = 29
> INFO :: Generating truncated reads
> INFO :: 38014884.0 reads to parse
> INFO :: 
> ----------
> n = 29
> INFO :: Generating truncated reads
> INFO :: Aligning reads
> INFO :: Aligning reads
> INFO :: Reporting aligned reads
> INFO :: Reporting aligned reads
> INFO :: 0 reads left to map.
> INFO :: 0 reads left to map.
> INFO :: 
> ----------
> n = 29
> INFO :: 
> ----------
> n = 29
> INFO :: Generating truncated reads
> INFO :: Generating truncated reads
> INFO :: Aligning reads
> INFO :: Aligning reads
> INFO :: Reporting aligned reads
> INFO :: 0 reads left to map.
> INFO :: Reporting aligned reads
> INFO :: 38014884.0 reads aligned / 38014884.0 total reads.
> INFO :: 0 reads left to map.
> INFO :: 38014884.0 reads aligned / 38014884.0 total reads.
> 38014884 read pairs in fastq files.
> 0.0% single end reads uniquely mapped with MQ > 30 (0/76029768)
> Writing fragment information...
> sort: cannot read: hicstuff_pipeline//unsorted_contacts_for.bed: No such file or directory

**Comment by cmdoret** [comment]
Thanks for the report, this happens when reads are shorter than truncation length. I have changed default truncation length to 20 in 80a515a226fbabfd9557d754016c58e50ffd1b49. I'll make sure to add a warning shortly.
