### ISSUE TITLE
pipeline with bowtie2 fails

### ISSUE THREAD

**Issue by psimion** [koszullab/hicstuff#21]
Hello,

While running hicstuff pipeline with default mapping tool (i.e. bowtie2) I ran into the following error, in which the bowtie2 index (however correctly created) is not detected by hicstuff.
```
> hicstuff pipeline -t $threads --iterative --plot -o $outdir -f $genome $fq1 $fq2
```

> LOGFILE: Adineta_vaga.Masurca_A1.Hi-C_reads/hicstuff_20190307152912.log
> Building bowtie2 index Avaga.Masurca_A1.fasta of Avaga.Masurca_A1.fasta
> Performing alignment and generating bed files...
> ERROR :: Reference index is missing, please build the bowtie2 index first.
> ERROR :: Reference index is missing, please build the bowtie2 index first.
> 55462178 read pairs in fastq files.
> awk: cannot open Adineta_vaga.Masurca_A1.Hi-C_reads/for.sam (No such file or directory)

I circumvented this issue by using the minimap2 option, in which case the pipeline correctly goes from start to end.
```
hicstuff pipeline -t $threads --minimap2 --iterative --plot -o $outdir -f $genome $fq1 $fq2
```
best,
paul

**Comment by cmdoret** [comment]
Hi Paul, 

Thanks for the report ! I have updated the index check in 2ca37d43771a209ae3e9171cc056f591e8d46297 and it should work now (on the github version, but I will make a new pip release soon enough)
