### ISSUE TITLE
filter3C causes display-related error on WSL

### ISSUE THREAD

**Issue by cmdoret** [koszullab/hicstuff#3]
As-is, the filter3C event throws an error due to the DISPLAY variable when used on the windows subsystem for linux or in an SSH session without X-forwarding.

Need to catch matplotlib/tkinter exceptions smoothly and import the related packages only if the --interactive flag is specified.

**Comment by baudrly** [comment]
Quick search yields the following suggestions:

1. Add the following snippet to the script, before importing pyplot
```
import matplotlib
matplotlib.use('Agg')
```

2. Set ```backend``` to ```Agg``` in one's ```matplotlibrc``` config file (could be unwieldy on Windows machines)

3. Run ```export DISPLAY=:0``` prior to running the script

4. Just wrap it into a try/except and skip figure generation for Windows machines, it's not essential.

I for one would go with either 1 or 4.

**Comment by cmdoret** [comment]
Fixed in db45e5eaf27a8c3242f8999182b4f6c7a7386853 by disabling interactive mode on windows machines.
