### ISSUE TITLE
option -b and -r/-f simultaneously

### ISSUE THREAD

**Issue by EvenStar69** [koszullab/hicstuff#30]
When trying to use both options -b without explicitly adding "kb" (e.g. "5" and not "5kb") and -r/-f, the output graph is not binned as expected:
`hicstuff view -b 5 -n -r CP020659.1 -f fragments_list.txt -o output abs_fragments_contacts_weighted.txt` 
doesn't work properly, but 
`hicstuff view -b 5kb -n -r CP020659.1 -f fragments_list.txt -o output abs_fragments_contacts_weighted.txt` 
and 
`hicstuff view -b 5kb -n -o output abs_fragments_contacts_weighted.txt` 
are working correctly

**Comment by cmdoret** [comment]
It seems to work as expected, but I should perhaps make it more clear in the docs; 
When you specify a basepair value (bp, kb, Mb, Gb), binning is done in fixed genomic bin length. However, when you don't specify any unit (-b 5), binning is done by subsampling groups of fragments together. In your case, bins are grouped by 5, which will result in a completely different binning than fixed genomic intervals of 5kb. Hope this helps, thanks for the feedback, I'll update the docs to make it clearer.
