### ISSUE TITLE
Help wanted on value error in io.py script

### ISSUE THREAD

**Issue by pedrocas81** [koszullab/hicstuff#35]
I was running a dummy test with hicstuff pipeline, but stumbled upon this error. I suspect it should be something related with the way I am feeding the arguments, particularly the single-end read fast file. It must be something very easy to sort out, but I wasn't able to figure it out. Any help would be greatly appreciated!
Thanks!
Pedro

Pedros-iMac:V_cholerae pedrooliveira$ hicstuff pipeline -t 4 -a minimap2 -e DpnII -o out/ -g NC_002505.fasta SRR3180921_1.fastq 
INFO :: ## hicstuff: v2.1.0 log file
INFO :: ## date: 2020-01-08 23:13:40
INFO :: ## enzyme: DpnII
INFO :: ## input1: SRR3180921_1.fastq 
INFO :: ## input2: None
INFO :: ## ref: NC_002505.fasta
INFO :: ---
[M::mm_idx_gen::0.084*0.92] collected minimizers
[M::mm_idx_gen::0.095*1.26] sorted minimizers
[M::main::0.095*1.25] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.095*1.25] mid_occ = 1000
[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.102*1.24] distinct minimizers: 484647 (99.36% are singletons); average occurrences: 1.019; average spacing: 5.996
[M::worker_pipeline::3.552*4.16] mapped 333924 sequences
[M::worker_pipeline::5.749*4.32] mapped 344101 sequences
[M::worker_pipeline::8.154*4.39] mapped 325632 sequences
[M::worker_pipeline::10.206*4.44] mapped 334306 sequences
[M::worker_pipeline::12.491*4.47] mapped 336155 sequences
[M::worker_pipeline::14.712*4.49] mapped 350149 sequences
[M::worker_pipeline::16.950*4.51] mapped 331440 sequences
[M::worker_pipeline::19.234*4.51] mapped 323934 sequences
[M::worker_pipeline::21.958*4.49] mapped 363066 sequences
[M::worker_pipeline::24.261*4.50] mapped 324676 sequences
[M::worker_pipeline::26.555*4.51] mapped 349066 sequences
[M::worker_pipeline::28.752*4.52] mapped 332211 sequences
[M::worker_pipeline::31.158*4.52] mapped 360453 sequences
[M::worker_pipeline::33.607*4.53] mapped 342744 sequences
[M::worker_pipeline::36.035*4.53] mapped 342936 sequences
[M::worker_pipeline::39.256*4.52] mapped 335029 sequences
[M::worker_pipeline::43.305*4.50] mapped 357511 sequences
[M::worker_pipeline::47.496*4.13] mapped 334610 sequences
[M::worker_pipeline::50.046*3.93] mapped 267892 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -2 -t 4 -ax sr NC_002505.fasta SRR3180921_1.fastq
[M::main] Real time: 50.156 sec; CPU: 196.796 sec; Peak RSS: 0.558 GB
[bam_sort_core] merging from 0 files and 4 in-memory blocks...
[M::mm_idx_gen::0.350*0.23] collected minimizers
[M::mm_idx_gen::0.361*0.34] sorted minimizers
[M::main::0.399*0.31] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.399*0.31] mid_occ = 1000
[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.404*0.32] distinct minimizers: 484647 (99.36% are singletons); average occurrences: 1.019; average spacing: 5.996
ERROR: failed to open file 'None'
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -2 -t 4 -ax sr NC_002505.fasta None
[M::main] Real time: 0.415 sec; CPU: 0.140 sec; Peak RSS: 0.040 GB
INFO :: Genome digested into 14206 fragments with a median length of 135.0
INFO :: 61% reads (single ends) mapped with Q >= 30 (3905370/6389835)
Traceback (most recent call last):
  File "/usr/local/bin/hicstuff", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/hicstuff/main.py", line 55, in main
    command.execute()
  File "/usr/local/lib/python3.7/site-packages/hicstuff/commands.py", line 731, in execute
    tmp_dir=self.args["--tmpdir"],
  File "/usr/local/lib/python3.7/site-packages/hicstuff/pipeline.py", line 803, in full_pipeline
    tmp_dir=tmp_dir,
  File "/usr/local/lib/python3.7/site-packages/hicstuff/io.py", line 1036, in sort_pairs
    sort_ver = list(map(int, sort_ver))
ValueError: invalid literal for int() with base 10: '(99)'

**Comment by axelcournac** [comment]
Hi Pedro
The data you use are WGS not hi-c right? The hicstuff pipeline contain several steps of filtering that may be not adapted to WGS data and filter most of your data and could explain why you dont have any files after. In any case, try the pipeline with 2 mates so I think you have to divide into 2 parts the initial file. 
Hope it helps
Axel

**Comment by cmdoret** [comment]
Hi Pedro, 

As @axelcournac  mentioned, you need to input two separate fastq files. Unfortunately, hicstuff does not understand interleaved paired reads in a single file.

Also, there was a second error in your log caused by an incompatibility with MacOS. I just pushed a new release, v2.1.2, which resolves this compatibility issue and yields more informative error messages when you only provide a single fastq file, to avoid confusion.

By the way, we normally test the software on Linux, so it is generally better to run it on linux than MacOS, but it should work anyways. What I would recommend to avoid any issue on macOS is either to [install the GNU coreutils](https://wikihub.berkeley.edu/display/drupal/Install+GNU+coreutils+and+other+CLI+utilities+on+MacOS) or [run our docker image](https://hub.docker.com/r/koszullab/hicstuff).

Cheers, 
Cyril

**Comment by pedrocas81** [comment]
Dear Axel and Cyril,

Thank you so much for your quick reply! 
It makes totally sense. I have now fastq-dumped paired-end hi-c data, splitted it, and fed it to hicstuff. I am using the docker image to avoid any dependence issue. However, I am getting the error below. I guess it should be something related with the way I am mounting my local folder (where I have the reference genome and fastq files), but not sure. Doing it this way, I see the tmp folder and for.bam file in /app/out/tmp/for.bam, but apparently he is not able to find it. Any help would be greatly appreciated.
And thanks once again for your help!
Best,
Pedro

$ docker run -it -p 8888:8888 -v /Users/pedrooliveira/Documents/MSSM/II_DNA_Structure/HiC/V_cholerae:/app koszullab/hicstuff pipeline -t 4 -a minimap2 -e DpnII -o /app/out/ --genome /app/NC_002505.fasta /app/SRR3180994_1.fastq /app/SRR3180994_2.fastq

INFO :: ## hicstuff: v2.1.0 log file
INFO :: ## date: 2020-01-09 21:30:55
INFO :: ## enzyme: DpnII
INFO :: ## input1: /app/SRR3180994_1.fastq 
INFO :: ## input2: /app/SRR3180994_2.fastq
INFO :: ## ref: /app/NC_002505.fasta
INFO :: ---
[M::mm_idx_gen::0.079*0.89] collected minimizers
[M::mm_idx_gen::0.110*1.18] sorted minimizers
[M::main::0.111*1.17] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.111*1.17] mid_occ = 1000
[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.117*1.11] distinct minimizers: 484647 (99.36% are singletons); average occurrences: 1.019; average spacing: 5.996
[M::worker_pipeline::15.898*1.68] mapped 549451 sequences
[M::worker_pipeline::29.279*1.28] mapped 549451 sequences
[M::worker_pipeline::43.792*1.11] mapped 549451 sequences
[M::worker_pipeline::55.377*1.07] mapped 549451 sequences
[M::worker_pipeline::69.627*1.00] mapped 549451 sequences
[M::worker_pipeline::82.355*0.98] mapped 549451 sequences
[M::worker_pipeline::95.220*0.96] mapped 549451 sequences
[M::worker_pipeline::109.975*0.92] mapped 549451 sequences
[M::worker_pipeline::124.772*0.90] mapped 549451 sequences
[M::worker_pipeline::137.984*0.89] mapped 549451 sequences
[M::worker_pipeline::150.029*0.89] mapped 549451 sequences
[M::worker_pipeline::161.720*0.88] mapped 549451 sequences
[M::worker_pipeline::175.069*0.88] mapped 549451 sequences
[M::worker_pipeline::189.521*0.86] mapped 549451 sequences
[M::worker_pipeline::202.057*0.86] mapped 549451 sequences
[M::worker_pipeline::214.949*0.85] mapped 549451 sequences
[M::worker_pipeline::228.007*0.85] mapped 549451 sequences
[M::worker_pipeline::240.585*0.84] mapped 549451 sequences
[M::worker_pipeline::254.219*0.84] mapped 549451 sequences
[M::worker_pipeline::267.676*0.84] mapped 549451 sequences
[M::worker_pipeline::281.050*0.83] mapped 549451 sequences
[M::worker_pipeline::297.051*0.82] mapped 549451 sequences
[M::worker_pipeline::310.770*0.82] mapped 549451 sequences
[M::worker_pipeline::324.865*0.82] mapped 549451 sequences
[M::worker_pipeline::339.732*0.81] mapped 549451 sequences
[M::worker_pipeline::353.213*0.81] mapped 549451 sequences
[M::worker_pipeline::370.881*0.79] mapped 549451 sequences
[M::worker_pipeline::399.725*0.76] mapped 549451 sequences
[M::worker_pipeline::425.370*0.73] mapped 549451 sequences
[M::worker_pipeline::446.868*0.71] mapped 549451 sequences
[M::worker_pipeline::467.639*0.70] mapped 549451 sequences
[M::worker_pipeline::488.293*0.69] mapped 549451 sequences
[M::worker_pipeline::515.632*0.67] mapped 549451 sequences
[M::worker_pipeline::538.497*0.65] mapped 549451 sequences
[M::worker_pipeline::561.113*0.64] mapped 549451 sequences
[M::worker_pipeline::584.107*0.63] mapped 549451 sequences
[M::worker_pipeline::615.778*0.61] mapped 549451 sequences
[M::worker_pipeline::639.643*0.60] mapped 549451 sequences
[M::worker_pipeline::666.253*0.58] mapped 549451 sequences
[M::worker_pipeline::700.150*0.57] mapped 549451 sequences
[M::worker_pipeline::734.622*0.55] mapped 549451 sequences
[M::worker_pipeline::762.893*0.54] mapped 549451 sequences
[M::worker_pipeline::787.373*0.52] mapped 549451 sequences
[M::worker_pipeline::819.922*0.50] mapped 429051 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -2 -t 4 -ax sr /app/NC_002505.fasta /app/SRR3180994_1.fastq
[M::main] Real time: 923.537 sec; CPU: 412.170 sec; Peak RSS: 0.772 GB
Killed
[M::mm_idx_gen::0.198*0.40] collected minimizers
[M::mm_idx_gen::0.222*0.50] sorted minimizers
[M::main::0.222*0.49] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.222*0.49] mid_occ = 1000
[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.230*0.52] distinct minimizers: 484647 (99.36% are singletons); average occurrences: 1.019; average spacing: 5.996
[M::worker_pipeline::42.451*0.53] mapped 549451 sequences
[M::worker_pipeline::77.019*0.39] mapped 549451 sequences
[M::worker_pipeline::116.198*0.33] mapped 549451 sequences
[M::worker_pipeline::189.916*0.24] mapped 549451 sequences
[M::worker_pipeline::309.006*0.17] mapped 549451 sequences
[M::worker_pipeline::328.833*0.19] mapped 549451 sequences
[M::worker_pipeline::353.453*0.21] mapped 549451 sequences
[M::worker_pipeline::379.957*0.22] mapped 549451 sequences
[M::worker_pipeline::405.529*0.23] mapped 549451 sequences
[M::worker_pipeline::433.357*0.23] mapped 549451 sequences
[M::worker_pipeline::458.369*0.24] mapped 549451 sequences
[M::worker_pipeline::480.232*0.25] mapped 549451 sequences
[M::worker_pipeline::504.815*0.25] mapped 549451 sequences
[M::worker_pipeline::529.461*0.26] mapped 549451 sequences
[M::worker_pipeline::553.903*0.27] mapped 549451 sequences
[M::worker_pipeline::578.896*0.27] mapped 549451 sequences
[M::worker_pipeline::601.600*0.28] mapped 549451 sequences
[M::worker_pipeline::623.660*0.28] mapped 549451 sequences
[M::worker_pipeline::646.565*0.28] mapped 549451 sequences
[M::worker_pipeline::670.938*0.29] mapped 549451 sequences
[M::worker_pipeline::702.461*0.29] mapped 549451 sequences
[ERROR] failed to write the results
Killed
INFO :: Genome digested into 14206 fragments with a median length of 135.0
[E::hts_open_format] Failed to open file /app/out/tmp/for.bam
Traceback (most recent call last):
  File "/miniconda/bin/hicstuff", line 8, in <module>
    sys.exit(main())
  File "/miniconda/lib/python3.7/site-packages/hicstuff/main.py", line 55, in main
    command.execute()
  File "/miniconda/lib/python3.7/site-packages/hicstuff/commands.py", line 731, in execute
    tmp_dir=self.args["--tmpdir"],
  File "/miniconda/lib/python3.7/site-packages/hicstuff/pipeline.py", line 782, in full_pipeline
    bam2pairs(bam1, bam2, pairs, info_contigs, min_qual=min_qual)
  File "/miniconda/lib/python3.7/site-packages/hicstuff/pipeline.py", line 140, in bam2pairs
    forward = ps.AlignmentFile(bam1, "rb")
  File "pysam/libcalignmentfile.pyx", line 741, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 940, in pysam.libcalignmentfile.AlignmentFile._open
FileNotFoundError: [Errno 2] could not open alignment file `/app/out/tmp/for.bam`: No such file or directory

**Comment by cmdoret** [comment]
Your command line seems alright ! Everything should work.
I reproduced the same command line with dummy data on OSX catalina with docker 19.03.5 and the latest docker image (hicstuff v2.1.2).

Please pull the latest hicstuff docker image (v2.1.2) using `docker pull koszullab/hicstuff:latest` and retry. If it doesn't work, make sure you have write permission in the output directory. If it works, feel free to close the issue :)

Cyril

**Comment by pedrocas81** [comment]
Thank you for your help!
It turns out that if I fastq-dump from SRA some Hi-C fast files without the --origfmt option, the pipeline will return an error afterwards. After dumping the files with that option, it worked properly. Thanks again!
Best,
Pedro
