### ISSUE TITLE
mapper choice

### ISSUE THREAD

**Issue by aderzelle** [koszullab/hicstuff#38]
Hello,
we compared minimap2 and bowtie2, and the results with minimap2 are: 57% of mapped reads, with bowtie2= 80% of mapped reads, which in my opininon makes minimap2 a rather horrible option. In our case we have 66 bp long reads. 

So I wondered if you shouldn't throw a warning at the user that if using minimap2 with reads < 100 bp  minimpa2 might fail to align a lot of the reads.

It's just a little suggeestion 

Thank you :)

**Comment by cmdoret** [comment]
That's a good idea. bowtie2 is always a better choice than minimap2 with reads < 100bp. Their minimap2 github recommends to use it only with reads >= 75bp. I 'll add a warning, thanks :)

**Comment by aderzelle** [comment]
And what about adding bwa? From my experience it's more sensitive but I don't have hard data at hand to prove it.

**Comment by cmdoret** [comment]
Right, someone is working on it, I'll keep you updated ;)

**Comment by nadegeguiglielmoni** [comment]
Hello,
It is now indicated in the help to avoid minimap2 for reads < 100 bp.
bwa has been added as a possibility for mapping with commit 'baeaa61', so you can update your version (with the github repo).
