### ISSUE TITLE
Can't install latest development

### ISSUE THREAD

**Issue by aderzelle** [koszullab/hicstuff#39]
Hello, 

```
pip3 install -e git+https://github.com/koszullab/hicstuff.git@master#egg=hicstuff
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'

```

I am getting this error. Thank you

**Comment by cmdoret** [comment]
Hi, 

I cannot reproduce your error, but it seems to be related to a specific version of pip3 / python and not specific to hicstuff. Personally I'd work in a conda environment, but several workarounds are suggested here:
https://stackoverflow.com/questions/28210269/importerror-cannot-import-name-main-when-running-pip-version-command-in-windo
