### ISSUE TITLE
single entry point with subcommands

### ISSUE THREAD

**Issue by cmdoret** [koszullab/hicstuff#4]
hicstuff currently has separate entry points. From a user point of view, it might be preferable to have a single entry point with subcommands. This would require a rework of the arguments parsing.
Currently we use a mix of argparse and docopt. It is apparently possible to handle subcommands with docopt, using a relatively simple wrapper script (minimal example shown here:  https://github.com/rgreinho/docopt-subcommands-example).

I could move everything to docopt and try making a wrapper script as shown in the example.
Would this be desirable ?

Goal: 
This should be the default behaviour:
```
$ hicstuff
Simple Hi-C pipeline.

usage:
    hicstuff [-hv] <command> [<args>...]

options:
    -h, --help                  shows the help
    -v, --version               shows the version

The subcommands are:
    filter3C   filters Hi-C pairs to exclude spurious events
    fraglist    digest genome into a list of fragments
    iteralign  iteratively aligns reads to a reference genome
    vizmap   visualize a Hi-C matrix
    yahcp     Hi-C pipeline to generate contact matrix from fastq files
```

**Comment by baudrly** [comment]
If we are using subcommands, might as well go with easy to understand names:

```
$ hicstuff
Simple Hi-C pipeline.

usage:
    hicstuff [-hv] <command> [<args>...]

options:
    -h, --help                  shows the help
    -v, --version               shows the version

The subcommands are:
    filter         filters Hi-C pairs to exclude spurious events
    digest      digest genome into a list of fragments
    iteralign   iteratively aligns reads to a reference genome
    view        visualize a Hi-C matrix
    pipeline   Hi-C pipeline to generate contact matrix from fastq files
```

**Comment by cmdoret** [comment]
Changes added in #5
