### ISSUE TITLE
Specify upper and lower bounds for the colorscale in view

### ISSUE THREAD

**Issue by aurelepiazza** [koszullab/hicstuff#41]
In order to be able to visually compare multiple conditions or samples (in a publication for example) it would be great to be able to fix the highest and lowest values of the colorscale in hicstuff view. The option -m somewhat allows to do this, but it remains approximate and time consuming to find the right threshold.

**Comment by cmdoret** [comment]
Good point, I just pushed  05f4d404df0ce76a3dcc1444c415a7c054938e87 which does the following:
-  Change behaviour of `--max`. By default `--max 3` now sets the saturation threshold (max value of colorbar) to 3. To use percentile, one needs to add % (e.g. `-M 99%`)
- Add option `--min` / `-m` which works exactly the same as `--max`. The max option is now `--max` / **`-M`**.
- The `--min` and `--max` thresholds are applied after transformations (e.g. log, exp, ...) and percentiles are computed on nonzero finite pixels.

If it passes unit tests, I'll make a new release !
