### ISSUE TITLE
[E::idx_find_and_load] Could not retrieve index file for 'out_hicstuff/tmp/f5b5560f/temp_alignment.bam'

### ISSUE THREAD

**Issue by aderzelle** [koszullab/hicstuff#43]
Hello, 

running

```
hicstuff pipeline --threads 10 --enzyme DpnII --iterative --outdir out_hicstuff --genome asm.fa $HIC1 $HIC2
```
I get the following error 

```
[E::idx_find_and_load] Could not retrieve index file for 'out_hicstuff/tmp/f5b5560f/temp_alignment.bam'
```

The pipeline keeps running though, so I am not sure if it's harmless or not. 

thank you!

**Comment by cmdoret** [comment]
Hi, 
This is weird, I cannot reproduce this error.
What version of samtools and hicstuff are you running ?

**Comment by aderzelle** [comment]
For samtools
Version: 1.9-40-g19b11f7 (using htslib 1.9-52-g6e86e38)
and the latest development version installed with pip 

I have to say it completed and I am able to launch instagraal... It's running now, doesn't appear to complain.

**Comment by cmdoret** [comment]
ok it should be good then !
This should not be a concern, especially if it happened towards the last iterations.
