### ISSUE TITLE
display the limits of the contigs on the matrix

### ISSUE THREAD

**Issue by jflot** [koszullab/hicstuff#45]
It would be nice to add a command to hicstuff that would automatically draw the limits between the input contigs on the matrix (e.g. as thin black lines). This would be particularly useful in cases when the limits between the contigs are not sharp on the matrix and it is sometimes difficult to see whether a particular translocation involves e.g. the end of chromosome 2 or the beginning of chromosome 3.

**Comment by cmdoret** [comment]
That's a good idea ! I'll add that in the next version when  I have time.

**Comment by cmdoret** [comment]
I added this feature in https://github.com/koszullab/hicstuff/commit/9a263f03627c8d308fa4fd093a19c450d56993c9 and  it is available in the development version already by using the `--lines` flag in `hicstuff view`.
