### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by sarah872** [koszullab/hicstuff#51]
Hi,
I have a couple of questions regarding the normalization procedure:
The output cool files of `hicstuff` have `weighted` in their filename. Are these already normalized matrices? If so, do you use SCN normalization?
Also, when I feed them into `cooler`,  do I need to run `cooler balance` first? For example, when I convert them to the bg2 file.

**Comment by cmdoret** [comment]
Hi @sarah872 

Despite the filename, hicstuff only outputs raw contacts matrices. If you export them to cooler, you'll need to run cooler balance.

The hicstuff view command allows to view the normalized (balanced) matrix when using the -n flag. This uses ICE normalization.

**Comment by sarah872** [comment]
Thanks for clarifying!
Therefore, I can either run `cooler balance` on my raw `hicstuff` matrix, or run `hicstuff view -n`, correct? What do you recommend?
I will also need to rebin some matrices, do I have to do that on the normalized matrix?

**Comment by cmdoret** [comment]
Hi,

`cooler balance` will compute and write the normalization weights to the cool file, whereas `hicstuff view -n` just displays the normalized contact map without modifying the file.

Rebinning is done on the raw contacts, so you will need to re-compute the balancing afterwards anyways.

**Comment by sarah872** [comment]
understood! thank you!
