### ISSUE TITLE
interpret distance law

### ISSUE THREAD

**Issue by gorliver** [koszullab/hicstuff#58]
Thank you for the useful tool!
Is there any document about the distance_law.pdf? I'm trying to understand the plot but seems there is no explaination about "Distance law", "Slope" and "P(s)". Can these plots be used for QC my Hi-C data?

**Comment by cmdoret** [comment]
Hi @gorliver 

This file shows the relationship between contacts and genomic distance. The x axis represents the log genomic distance between pairs of loci, and the y axis shows their log interaction frequency.

This curve and its slope can give general information about chromatin compaction. For example, it changes between cell cycle phases. It can indeed be useful as a QC, as you would expect the curve from different replicates to be nearly identical.

**Comment by gorliver** [comment]
Thanks @cmdoret!
