### ISSUE TITLE
Error at the end of pipeline execution

### ISSUE THREAD

**Issue by alexvasilikop** [koszullab/hicstuff#61]
Hello,

I have the following error when I run the hicstuff pipeline for one genome I am using. The command is the following:
$ hicstuff pipeline -t $threads -a $mapper --plot -e DpnII,HinfI -o $outdir -g $genome $fq1 $fq2

I used bowtie for the mapping. What might be the problem?

###
37.78% overall alignment rate
[bam_sort_core] merging from 48 files and 8 in-memory blocks...
128005844 reads; of these:
  128005844 (100.00%) were unpaired; of these:
    79672993 (62.24%) aligned 0 times
    19837496 (15.50%) aligned exactly 1 time
    28495355 (22.26%) aligned >1 times
37.76% overall alignment rate
[bam_sort_core] merging from 48 files and 8 in-memory blocks...
INFO :: 25% reads (single ends) mapped with Q >= 30 (64184821/256011688)
Traceback (most recent call last):
  File "/usr/local/bin/hicstuff", line 11, in <module>
    load_entry_point('hicstuff', 'console_scripts', 'hicstuff')()
  File "/src/hicstuff/hicstuff/main.py", line 55, in main
    command.execute()
  File "/src/hicstuff/hicstuff/commands.py", line 733, in execute
    tmp_dir=self.args["--tmpdir"],
  File "/src/hicstuff/hicstuff/pipeline.py", line 808, in full_pipeline
    hcd.attribute_fragments(pairs, pairs_idx, restrict_table)
  File "/src/hicstuff/hicstuff/digest.py", line 229, in attribute_fragments
    int(pair["pos1"]) - 1, restriction_table[pair["chr1"]]
  File "/src/hicstuff/hicstuff/digest.py", line 355, in find_frag
    "Read position is larger than last entry in restriction table."
ValueError: Read position is larger than last entry in restriction table.

**Comment by ABignaud** [comment]
Hello, 

Your issue is that when hicstuff attributes the fragments to the mapped in go outside the length of the given chromosome. 
As you use bowtie2 and hicstuff piepeline, we shouldn't have issue of mapping positions. I think the issue comes with your fasta. Is it possible that you have special character in the names of the fasta sequence, or duplicated sequence names ?

Amaury

**Comment by alexvasilikop** [comment]
Ok the problem was apparently the headers of the fasta file.
When I changed them from e.g.:

>ctg000000 type:s:linear length:i:361523 node:i:27

to:

>ctg000000

The pipeline ends without problems.

Many thanks
