### ISSUE TITLE
hicstuff pipeline Python 3.9 error

### ISSUE THREAD

**Issue by Overcraft90** [koszullab/hicstuff#63]
Hi there,

I'm using `hicstuff pipeline` with the following command:

> hicstuff pipeline -t 16 -a minimap2 -e DpnII -o 2.HG00733/instaGRAAL_hap1/ -g 2.HG00733/HG00733_hifi.hic.hap1.fasta 2.HG00733/HG00733_hic1.fastq.gz 2.HG00733/HG00733_hic2.fastq.gz

But, unfortunately, I getting this error ([hicstuff.log](https://github.com/koszullab/hicstuff/files/8695392/hicstuff.log)) which seems related to _**Python3.9**_ and I've haven't experienced before.

To what is it related to? The only thing I can think off is that I might have swapped the HiC datasets in the command, so _hic1_ in _hic2_ and vice-versa. However, I don't think this will make any difference. Please, let me know.

Thanks in advance.

**Comment by Overcraft90** [comment]
Hi again,

Just as reference I run again the command for human individual HG002, similarly to what I have done for HG00733 in the comment above:

> hicstuff pipeline -t 16 -a minimap2 -e DpnII -o 1.HG002_trial/instaGRAAL_hap1/ -g 1.HG002_trial/HG002_hifi.hic.hap1.fasta 1.HG002_trial/HG002_hic1.fastq.gz 1.HG002_trial/HG002_hic2.fastq.gz

And, in this case, I didn't get any error ([hicstuff-2.log](https://github.com/koszullab/hicstuff/files/8698508/hicstuff-2.log)). Could this be ralated to the _-e_ flag referring to the restriction enzyme, again it seems unlikely to me but I would like to know (_e.g._ the wrong **r. e.** could lead to this type of errors).

One last thing, I thought the issue could be related to the number of scaffolds and/or to how much the assembly is fragmented. HG00733, despite being my second best assembly, is still worst than HG002 in terms of accuracy and contiguity. Is maybe this one the root for the error I'm getting (_e.g._ my mobile workstation cannot compute such an assembly).

I monitored both HD storage space and CPU and RAM utilization with `htop` and there seemed to be no problems with that..., so let me know how can I fix this because the error prevents `hicstuff` from generating the _**abs_fragments_contacts_weighted.txt**_ file necessary for downstream scaffolding with `instaGRAAL`.

Thanks.

**Comment by ABignaud** [comment]
Hi, 
I think it's an issue with the name of the sequence queries in your fasta. I think there are some special characters. As in this previous issue: #61
Could you send me an example of query name in the two different fasta files ? 
So if the case removing special characters and replacing them with '_' should do the trick.
Thanks

**Comment by Overcraft90** [comment]
I will be very happy to do so; however, I'm not sure on how to send you the query name in my fasta files...

What I can help you with is sending you some screenshots of how the look like:

_**hap1.fasta**_
![Screenshot from 2022-05-16 12-32-19](https://user-images.githubusercontent.com/98895614/168574894-9e90980c-07c5-4d1c-adad-368e897a908a.png)

**_hic1.fastq.gz_**
![Screenshot from 2022-05-16 12-32-39](https://user-images.githubusercontent.com/98895614/168574984-c7f7f4e2-237f-487b-8e9b-0f4df0c113c9.png)

_**hic2.fastq.gz**_
![Screenshot from 2022-05-16 12-32-52](https://user-images.githubusercontent.com/98895614/168575065-4046b18c-a9b1-4c84-942c-a3327a9cea46.png)

What I can see is that the headers of the HiC datasets contain some special characters, is this what you meant? I hope so, if not please let me know how can I get the info you need.

Thanks

**Comment by ABignaud** [comment]
Ok can you do these commands: 
`grep ">" HG00733_hifi.hic.hap1.fasta | head`
`grep ">" HG002_hifi.hic.hap1.fasta | head`

Thanks

**Comment by ABignaud** [comment]
Ok it doesn't seem that the issue is from the fasta. Do you still have the tmp folder in your output directory ? Can you check the bam files ? You can run the following command:
```sh
ls -lh 2.HG00733/instaGRAAL_hap1/tmp/
samtools view 2.HG00733/instaGRAAL_hap1/tmp/for.bam | head
samtools view 2.HG00733/instaGRAAL_hap1/tmp/rev.bam | head
```

**Comment by Overcraft90** [comment]
Hi and sorry for answering late,

I have to generate again both _**for.bam**_ and _**rev.bam**_ files... I took about 8h and, unfortunately, I was traveling the past two days...

Here is the output for the `tmp` folder and the `head` for both _**.bam**_ files:
![Screenshot from 2022-05-18 09-40-36](https://user-images.githubusercontent.com/98895614/168985058-858697fc-43b2-43c0-9daa-8d8b5635de6d.png)

Let me know whether you can see any discrepancy, thanks.

**Comment by ABignaud** [comment]
Hi,

Sorry for my late answer. It seems that the read ID from your two fastq forward and reverse are different. For the forward it's ERR4501134 and ERR4501109 for the reverse. If they come from the same sequencing, you should their id to correspond. You can do a command like:

```sh
zcat old_hic2.fastq.gz | sed 's/ERR4501109/ERR4501134/' > new_hic2.fastq
gzip new_hic2.fastq
```
Then launch again hicstuff. 

If you want to avoid to realign your reads you can do:

```sh 
samtools view 2.HG00733/instaGRAAL_hap1/tmp/rev.bam | sed 's/ERR4501109/ERR4501134/' > 2.HG00733/instaGRAAL_hap1/tmp/rev2.sam
samtools view -b 2.HG00733/instaGRAAL_hap1/tmp/rev2.sam >  2.HG00733/instaGRAAL_hap1/tmp/rev2.bam
```
Then you can launch hicstuff pipeline as before, adding the `--start bam` option and you can put your bam file instead of the fastq as arguments.
