### ISSUE TITLE
rebin output format

### ISSUE THREAD

**Issue by etiennejourdier** [koszullab/hicstuff#66]
2 small issues regarding the rebin command output : 
- the .frags.tsv file has an incoherent extension .frag.tsv without the s
- The first example in the [rebin setion on readthedocs](https://hicstuff.readthedocs.io/en/latest/notebooks/demo_cli.html#Rebinning-existing-matrices) shows a --out parameter which does not exist (the second example is fine)

**Comment by cmdoret** [comment]
Hi @etiennejourdier, thanks for reporting the issues !
They have been addressed in b1b751a6213d25ff7f79baa92be5def514c847b3 and c32f3c975a86b8406471d293eced34ed33322e9b respectively and should (soon) make it into the next release.
