### ISSUE TITLE
pipeline option to exclude chromosomes

### ISSUE THREAD

**Issue by cmdoret** [koszullab/hicstuff#72]
There should be an option in `hicstuff pipeline` to exclude chromosomes from the output matrix (post-mapping).

**Comment by js2264** [comment]
Added in https://github.com/koszullab/hicstuff/commit/5963b24948464e66d9795b654b5fde408d8f09b9 (included in [release 3.2.0](https://github.com/koszullab/hicstuff/milestone/1))
