### ISSUE TITLE
add option to plot fragment threshold 

### ISSUE THREAD

**Issue by tfoutelrodier** [koszullab/hicstuff#8]
Maybe add an option to plot the fragment threshold for loop and uncut without having to keep all intermediary files ? I think it would be useful to be able to check that there's no weird situation throwing the automatic threshold detection off and that would require manual step by step processing.

**Comment by cmdoret** [comment]
Good idea, added this feature in 3ffe9237a6b5370af32e45b24e4831c591587cc6 and included this in version 0.1.13. You can now specify the `--plot` option in `hicstuff pipeline` and this will save all graphs into a `plots` subfolder of the output directory.
