### ISSUE TITLE
problem to rebin a graal format matrix

### ISSUE THREAD

**Issue by mmarbout** [koszullab/hicstuff#87]
(metator) ubuntu@machine011e5f12-3709-40a7-9316-3358cbab6008:~$ head Tuto_MetaTOR/contact_map_1/NODE_1078_len_298687.frags.tsv
id	chrom	start_pos	end_pos	size	gc_content
1	NODE_1078_len_298687	0	106	106	0.005
2	NODE_1078_len_298687	106	143	37	0.004324324324324324
3	NODE_1078_len_298687	143	151	8	0.005
4	NODE_1078_len_298687	151	218	67	0.0035820895522388056
5	NODE_1078_len_298687	218	572	354	0.00327683615819209
6	NODE_1078_len_298687	572	774	202	0.003465346534653465
7	NODE_1078_len_298687	774	838	64	0.00484375
8	NODE_1078_len_298687	838	982	144	0.004652777777777778
9	NODE_1078_len_298687	982	1025	43	0.004186046511627907
(metator) ubuntu@machine011e5f12-3709-40a7-9316-3358cbab6008:~$ head Tuto_MetaTOR/contact_map_1/NODE_1078_len_298687.chr.tsv 
contig	length	n_frags	cumul_length
NODE_1078_len_298687	298687	2990	0
(metator) ubuntu@machine011e5f12-3709-40a7-9316-3358cbab6008:~$ head Tuto_MetaTOR/contact_map_1/NODE_1078_len_298687.mat.tsv 
2990	2990	98482
0	113	1
0	159	1
0	219	2
0	307	2
0	337	1
0	469	1
0	573	1
0	700	3
0	1100	1
(metator) ubuntu@machine011e5f12-3709-40a7-9316-3358cbab6008:~$ hicstuff rebin -b 10kb -f Tuto_MetaTOR/contact_map_1/NODE_1078_len_298687.frags.tsv -c Tuto_MetaTOR/contact_map_1/NODE_1078_len_298687.chr.tsv Tuto_MetaTOR/contact_map_1/NODE_1078_len_298687.mat.tsv Tuto_MetaTOR/contact_map_1/NODE_1078_len_298687_10kb
Traceback (most recent call last):
  File "/var/lib/miniforge/envs/metator/bin/hicstuff", line 10, in <module>
    sys.exit(main())
  File "/var/lib/miniforge/envs/metator/lib/python3.10/site-packages/hicstuff/main.py", line 57, in main
    command.execute()
  File "/var/lib/miniforge/envs/metator/lib/python3.10/site-packages/hicstuff/commands.py", line 1108, in execute
    hic_map, _ = hcs.bin_bp_sparse(hic_map, frags.start_pos, binning)
AttributeError: module 'hicstuff.stats' has no attribute 'bin_bp_sparse'

**Comment by js2264** [comment]
Fixed in https://github.com/koszullab/hicstuff/commit/343d58e8e437413bc784681a690e0af7f255f0c4. hicstuff 3.2.4 should work, you can install it with `pip install hicstuff==3.2.4`. Let me know if you still have issues.
